### ISSUE TITLE
when txt email is send, assert_body_contains raises an error

### ISSUE THREAD

**Issue by Bergiu** [ambient-innovation/ai-django-core#1]
I'm sending an email as txt not html and when i try to use `assert_body_contains`, this error is raised:
```
Traceback (most recent call last):
  File "/home/user/workspace/project/user_auth/tests.py", line 35, in test_get_profile
    mails.assert_body_contains('receiving')
  File "/home/user/workspace/project/venv/lib/python3.8/site-packages/ai_django_core/mail/services/tests.py", line 197, in assert_body_contains
    self.assertIn(search_str, self._get_html_content(), msg=msg)
  File "/home/user/workspace/project/venv/lib/python3.8/site-packages/ai_django_core/mail/services/tests.py", line 108, in _get_html_content
    return self._match_list[0].alternatives[0][0]
IndexError: list index out of range
```

I think there is missing an option to disable the assertIn check in line 197 in services/tests.py or a check `if len(alternatives) > 0`.

**Comment by GitRon** [comment]
True, we never use only-text-mails. Will put in the if condition.

**Comment by Bergiu** [comment]
Thanks

**Comment by GitRon** [comment]
OK, actually you are running an old version. I already caught this excpetion. Still, the validation would fail if you have no HTML part set. I fixed it an will release a new version soon. Thanks for the info!

**Comment by GitRon** [comment]
Fixed 🎉

**Comment by Bergiu** [comment]
Thanks for your library
